# Site settings
title: "How's The Roads?"
description: "Live traffic cameras and current weather conditions for Kansas City roads"
url: "https://howstheroads.com"
author: "How's The Roads?"

# Build settings
markdown: kramdown
permalink: pretty